// This file is autogenerated by VESC Tool

#ifndef MCCONF_BBSHD_H_
#define MCCONF_BBSHD_H_

// PWM Mode
#define MCCONF_PWM_MODE 1

// Commutation Mode
#define MCCONF_COMM_MODE 0

// Motor Type
#define MCCONF_DEFAULT_MOTOR_TYPE 2

// Sensor Mode
#define MCCONF_SENSOR_MODE 0

// Motor Current Max
#define MCCONF_L_CURRENT_MAX 82.0

// Motor Current Max Brake
#define MCCONF_L_CURRENT_MIN -20

// Battery Current Max
#define MCCONF_L_IN_CURRENT_MAX 65

// Battery Current Max Regen
#define MCCONF_L_IN_CURRENT_MIN -20

// Input Current Limit Map Start
#define MCCONF_L_IN_CURRENT_MAP_START 0.9

// Input Current Map Filter
#define MCCONF_L_IN_CURRENT_MAP_FILTER 0.005

// Absolute Maximum Current
#define MCCONF_L_MAX_ABS_CURRENT 150

// Max ERPM Reverse
#define MCCONF_L_RPM_MIN -4200

// ERPM Limit Start
#define MCCONF_L_RPM_START 0.8

// Minimum Input Voltage
#define MCCONF_L_MIN_VOLTAGE 12

// Maximum Input Voltage
#define MCCONF_L_MAX_VOLTAGE 85

// Battery Voltage Regen Cutoff Start
#define MCCONF_L_BATTERY_REGEN_CUT_START 1000

// Battery Voltage Regen Cutoff End
#define MCCONF_L_BATTERY_REGEN_CUT_END 1100

// Slow ABS Current Limit
#define MCCONF_L_SLOW_ABS_OVERCURRENT 0

// MOSFET Temp Cutoff Start
#define MCCONF_L_LIM_TEMP_FET_START 85

// MOSFET Temp Cutoff End
#define MCCONF_L_LIM_TEMP_FET_END 90

// Motor Temp Cutoff Start
#define MCCONF_L_LIM_TEMP_MOTOR_START 95

// Motor Temp Cutoff End
#define MCCONF_L_LIM_TEMP_MOTOR_END 105

// Acceleration Temperature Decrease
#define MCCONF_L_LIM_TEMP_ACCEL_DEC 0.02

// Minimum Duty Cycle
#define MCCONF_L_MIN_DUTY 0.05

// Maximum Duty Cycle
#define MCCONF_L_MAX_DUTY 0.95

// Maximum Wattage
#define MCCONF_L_WATT_MAX 4000

// Maximum Braking Wattage
#define MCCONF_L_WATT_MIN -1000

// Duty Cycle Current Limit Start
#define MCCONF_L_DUTY_START 1

// Current KP
#define MCCONF_FOC_CURRENT_KP 0.22

// Current KI
#define MCCONF_FOC_CURRENT_KI 39

// Zero Vector Frequency
#define MCCONF_FOC_F_ZV 30000

// Dead Time Compensation
#define MCCONF_FOC_DT_US 0.14

// Sensor Mode
#define MCCONF_FOC_SENSOR_MODE 2

// Motor Inductance (L)
#define MCCONF_FOC_MOTOR_L 0.000223458

// Motor Inductance Difference (Lq - Ld)
#define MCCONF_FOC_MOTOR_LD_LQ_DIFF 0.000045

// Motor Resistance (R)
#define MCCONF_FOC_MOTOR_R 0.041

// Motor Flux Linkage (?)
#define MCCONF_FOC_MOTOR_FLUX_LINKAGE 0.01944

// Observer Gain (x1M)
#define MCCONF_FOC_OBSERVER_GAIN 2330000

// Observer Gain At Minimum Duty
#define MCCONF_FOC_OBSERVER_GAIN_SLOW 0.1

// Duty Downramp Kp
#define MCCONF_FOC_DUTY_DOWNRAMP_KP 10

// Duty Downramp Ki
#define MCCONF_FOC_DUTY_DOWNRAMP_KI 200

// Start Current Decrease
#define MCCONF_FOC_START_CURR_DEC 1 // if we want less phase amps down low decrease this value (can help avoid stripping nylon gear on low rpm hard acceleration)

// Start Current Decrease ERPM
#define MCCONF_FOC_START_CURR_DEC_RPM 3000 

// Openloop ERPM
#define MCCONF_FOC_OPENLOOP_RPM 500

// Openloop Time
#define MCCONF_FOC_SL_OPENLOOP_TIME 0.1

// Openloop Current Boost
#define MCCONF_FOC_SL_OPENLOOP_BOOST_Q 3

// Openloop Current Max
#define MCCONF_FOC_SL_OPENLOOP_MAX_Q 6

// Hall Table [1]
#define MCCONF_FOC_HALL_TAB_1 100

// Hall Table [2]
#define MCCONF_FOC_HALL_TAB_2 33

// Hall Table [3]
#define MCCONF_FOC_HALL_TAB_3 67

// Hall Table [4]
#define MCCONF_FOC_HALL_TAB_4 167

// Hall Table [5]
#define MCCONF_FOC_HALL_TAB_5 133

// Hall Table [6]
#define MCCONF_FOC_HALL_TAB_6 0

// Hall Interpolation ERPM
#define MCCONF_FOC_HALL_INTERP_ERPM 250

// Sensored ERPM Start
#define MCCONF_FOC_SL_ERPM_START 1500

// Sensorless ERPM
#define MCCONF_FOC_SL_ERPM 3000

// Control Sample Mode
#define MCCONF_FOC_CONTROL_SAMPLE_MODE 0 // flipsky is able to sample only in V0 (low side shunts only)

// Current Sample Mode
#define MCCONF_FOC_CURRENT_SAMPLE_MODE 0

// Saturation Compensation Mode
#define MCCONF_FOC_SAT_COMP_MODE 3 //lambda and factor

// Saturation Compensation Factor
#define MCCONF_FOC_SAT_COMP 0.22

// Temp Comp
#define MCCONF_FOC_TEMP_COMP 1

// Temp Comp Base Temp
#define MCCONF_FOC_TEMP_COMP_BASE_TEMP 25.0

// Current Filter Constant
#define MCCONF_FOC_CURRENT_FILTER_CONST 0.1

// Current Controller Decoupling
#define MCCONF_FOC_CC_DECOUPLING 0 // no luck in enabling it yet

// Observer Type
#define MCCONF_FOC_OBSERVER_TYPE 3 // mxlemming-lambda-comp -> possibly the best observer for bbshd

// Offset Calibration Mode
#define MCCONF_FOC_OFFSETS_CAL_MODE 0

// Enable Phase Filters
#define MCCONF_FOC_PHASE_FILTER_ENABLE 1

// Disable Phase Filter Fault Code
#define MCCONF_FOC_PHASE_FILTER_DISABLE_FAULT 1

// Maximum ERPM for phase filters
#define MCCONF_FOC_PHASE_FILTER_MAX_ERPM 5000

// MTPA Algorithm Mode
#define MCCONF_FOC_MTPA_MODE 2 // IQ Measured

// Field Weakening Duty Start
#define MCCONF_FOC_FW_DUTY_START 0.85

// Field Weakening Ramp Time
#define MCCONF_FOC_FW_RAMP_TIME 0.2

// Q Axis Current Factor
#define MCCONF_FOC_FW_Q_CURRENT_FACTOR 0.1

// Backoff Gain
#define MCCONF_FOC_FW_BACKOFF 2

// Speed Tracker Position Source
#define MCCONF_FOC_SPEED_SOURCE 1

// Short Low-Side FETs on Zero Duty
#define MCCONF_FOC_SHORT_LS_ON_ZERO_DUTY 0

// Overmodulation Factor
#define MCCONF_FOC_OVERMOD_FACTOR 1.05

// Maximum VD Magnitude
#define MCCONF_FOC_MAG_VD_MAX 0.9

// PID Loop Rate
#define MCCONF_SP_PID_LOOP_RATE 5

// Speed PID Kp
#define MCCONF_S_PID_KP 0.004

// Speed PID Ki
#define MCCONF_S_PID_KI 0.004

// Speed PID Kd
#define MCCONF_S_PID_KD 0.0001

// Speed PID Kd Filter
#define MCCONF_S_PID_KD_FILTER 0.2

// Minimum ERPM
#define MCCONF_S_PID_MIN_RPM 800

// Allow Braking
#define MCCONF_S_PID_ALLOW_BRAKING 1

// Ramp eRPMs per second
#define MCCONF_S_PID_RAMP_ERPMS_S -1

// Speed Source
#define MCCONF_S_PID_SPEED_SOURCE 0

// Position PID Kp
#define MCCONF_P_PID_KP 0.03

// Position PID Ki
#define MCCONF_P_PID_KI 0

// Position PID Kd
#define MCCONF_P_PID_KD 0.0004

// Position PID Kd Process
#define MCCONF_P_PID_KD_PROC 0.00035

// Position PID Kd Filter
#define MCCONF_P_PID_KD_FILTER 0.2

// Position Angle Division
#define MCCONF_P_PID_ANG_DIV 1

// Gain Decrease Angle
#define MCCONF_P_PID_GAIN_DEC_ANGLE 0

// Motor Temperature Sensor Type
#define MCCONF_M_MOTOR_TEMP_SENS_TYPE 7

// Minimum Current
#define MCCONF_CC_MIN_CURRENT 1.0

// Motor Poles
#define MCCONF_SI_MOTOR_POLES 8

// Gear Ratio
#define MCCONF_SI_GEAR_RATIO 21.9

// Wheel Diameter
#define MCCONF_SI_WHEEL_DIAMETER 0.71

// Battery Type
#define MCCONF_SI_BATTERY_TYPE 0

// Battery Capacity
#define MCCONF_SI_BATTERY_AH 15

// Motor No Load Current
#define MCCONF_SI_MOTOR_NL_CURRENT 0.5

// MCCONF_BBSHD_H_
#endif

